# Generated by Django 3.0 on 2020-08-03 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_structure', models.CharField(blank=True, max_length=1, null=True)),
                ('algorithm', models.CharField(blank=True, max_length=1, null=True)),
                ('cplusplus', models.CharField(blank=True, max_length=1, null=True, verbose_name='C++')),
                ('python', models.CharField(blank=True, max_length=1, null=True)),
                ('java', models.CharField(blank=True, max_length=1, null=True)),
                ('ip', models.CharField(blank=True, max_length=155, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polling', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
